version: "3.2"
services:
  spark-worker1a:
    container_name: spark-worker1a
    image: spydernaz/spark-worker:latest
    networks:
      - br-n-spark
    extra_hosts:
      - spark-master:10.0.0.200
      - spark-worker2a:10.0.0.24
      - spark-worker3a:10.0.0.200
      - spark-worker4a:10.0.0.200
      - spark-submit:172.42.0.5
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=16G
      - SPARK_DRIVER_MEMORY=16G
      - SPARK_EXECUTOR_MEMORY=16G
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data

networks:
   br-n-spark:
     driver: bridge
